#!/usr/bin/env bash
# Configures /etc/hosts to redirect localhost and facebook.com

# Update localhost to resolve to 127.0.0.2
# We use sed to find the line starting with 127.0.0.1 and replace it
sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

# Redirect facebook.com to 8.8.8.8
# We append this to the end of the file
echo "8.8.8.8 facebook.com" >> /etc/hosts
